IMPLICIT NONE
REAL TOTAL,TOTAL_MEAN
INTEGER I,N
TOTAL = 0.0
N = 0
DO I=1,10,2
    TOTAL = TOTAL+I
    N = N+1
    WRITE(*,20) I,TOTAL
END DO
WRITE(*,*) 'TOTAL = ',TOTAL
20 FORMAT(I3,F15.2)
TOTAL_MEAN = TOTAL/FLOAT(N)
WRITE(*,*) 'TOTAL_MEAN = ',TOTAL_MEAN

END

