! FT_1102_Ch07_0301_1.f90
IMPLICIT NONE
REAL BALANCE,PAYMENT,TOTAL
INTEGER MON
READ(*,*) BALANCE
Mon = 1;TOTAL = 0
BALANCE = BALANCE*1.05
DO while (BALANCE .GT. 1000.)
    WRITE(*,*) BALANCE
    PAYMENT = 0.3*BALANCE
    WRITE(*,*) 'MON->',MON,'Pay->',PAYMENT
    MON = MON+1
    TOTAL = TOTAL+PAYMENT
    BALANCE = (BALANCE-PAYMENT)*1.05
    WRITE(*,*) 'B=',BALANCE
END DO
WRITE(*,*) '2 Mon->',Mon,' Last Pay->',BALANCE
TOTAL = TOTAL+BALANCE
WRITE(*,*) 'TOTAL=',TOTAL
END
