IMPLICIT NONE
REAL X,XX,SEG_V(100),ACCUM,FINALA
INTEGER NUM_TERMS,I,J
REAL XVAL,VAL2
WRITE(*,*) 'Input X & NUM_TERMS>'
READ(*,*) X,NUM_TERMS
SEG_V(1) = X*X
ACCUM = 2.0
XVAL = X*X
J = -1
VAL2=2.0
XX=X*X
DO I=2,NUM_TERMS
    ACCUM = ACCUM*(2*I-1)*(2*I)
    XVAL = XVAL*XX
    VAL2 = VAL2*4
    SEG_V(I) = J*VAL2*XVAL/ACCUM
    WRITE(*,100) 'I=',I,VAL2,XVAL,ACCUM,SEG_V(I)
    J = -1*J
END DO
100 FORMAT(A3,I4,4F10.4)
FINALA = 0.0
DO I = 1,NUM_TERMS
    FINALA = FINALA+SEG_V(I)
    WRITE(*,120)I,SEG_V(I),FINALA
END DO
120 FORMAT(I4,2F10.4)
END
