IMPLICIT NONE
INTEGER A1,A2,A3,REC_FN_FACT
A1=5
WRITE(*,*) 'A1=',A1
A2=REC_FN_FACT(A1)
WRITE(*,*) 'A2=',A2
END
RECURSIVE FUNCTION REC_FN_FACT(N) RESULT(ANS1)
INTEGER, INTENT(IN)::N
INTEGER:: ANS1
WRITE(*,*) '2 N=',N
IF(N>=1) THEN
    ANS1 = N*REC_FN_FACT(N-1)
    WRITE(*,*) '2 ans1=',ans1,' N=',N
ELSE
    ANS1 = 1
END IF
WRITE(*,*) '3..ANS1=',ANS1,' N=',N
END FUNCTION REC_FN_FACT
