! CH06_0401_5
IMPLICIT none
REAL X,RESULT1,XX,AX,ACCUM
INTEGER N_TERMS,N_COUNT,KK
WRITE(*,*) 'INPUT X,N_TERMS >>'
READ(*,*) X,N_TERMS
WRITE(*,*) 'N_TERMS='N_TERMS
RESULT1=X
XX=X*X
N_COUNT = 2
AX=X
ACCUM=1
KK = 1
100 IF (N_TERMS .GE. N_COUNT) then
    ACCUM = ACCUM*(2)
    END IF

end
