! CH06_0401_5
! 計算sin(x)的Taylor展開式，輸入一x值及欲取項次
IMPLICIT none
REAL X,RESULT1,XX,AX,ACCUM
INTEGER N_TERMS,N_COUNT,KK
WRITE(*,*) 'INPUT X,N_TERMS >>'
READ(*,*) X,N_TERMS
WRITE(*,*) 'N_TERMS=',N_TERMS
RESULT1=X
XX=X*X
N_COUNT = 2
AX=X
ACCUM=1
KK = 1
100 IF (N_TERMS .GE. N_COUNT) then
        ACCUM = ACCUM*(2*N_COUNT-1)*(2*N_COUNT-2)
        AX = -AX*XX
        RESULT1 = RESULT1 + KK*AX/ACCUM
        N_COUNT = N_COUNT + 1
        GO TO 100
    END IF !N_TERMS>=N_COUNT
WRITE(*,'(A10,F12.6,A10,I6,A10,F12.6)') 'X=',X,'N_TERMS=',N_TERMS,'RESULT1=',RESULT1
end
